<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">

<?php

$strMethods = Mage::getStoreConfig('payment/moduslink/methods');
$arrMethods = explode(",", $strMethods); //@todo Replace by constant instead
$sourceModel = Mage::getModel("bluecom_moduslink/system_config_source_paymentMethods")->toOptionArray();

$apiMdHandler = Mage::helper("bluecom_moduslink/api");
$arrPMByGroup = $apiMdHandler->groupMDMethods($arrMethods);
$arrPmLabel = array(
    "paypal" => "PayPal",
    "creditcard" => "Credit Cards",
);



if(!empty($arrMethods)):
?>

    <ul class="ml-items">
        <?php foreach ($arrMethods as $strMethod):$id  = strtolower($strMethod); ?>
            <li class="item">
                <input type="radio" name="payment[md_payment_method]" value="<?php echo $strMethod  ?>" id="<?php echo $id  ?>" />
                <label for="<?php echo $id  ?>"><?php echo $sourceModel[$strMethod]["label"]  ?></label>
            </li>
        <?php endforeach; ?>
    </ul>

<?php endif; ?>

<?php /*if(!empty($arrPMByGroup)):$index = 0;?>
    <?php foreach ($arrPMByGroup as $group => $arrMethod) : ?>
        <dt>
            <input type="radio"
                   id="p_method_md_<?php echo $group ?>"
                   name="payment[method]"
                   data-type="moduslink"
                   onclick="payment.switchMethod('md_<?php echo $group ?>', this); "
                   value="MD_<?php echo $group  ?>"
                   class="radio"
                />
            <label for="p_method_md_<?php echo $group ?>"><?php echo $arrPmLabel[$group]  ?></label>
        </dt>
    <?php endforeach; ?>
<?php endif;*/ ?>
</div>
