<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">

<?php

$strMethods = Mage::getStoreConfig('payment/moduslink/methods');
$arrMethods = explode(",", $strMethods); //@todo Replace by constant instead
$sourceModel = Mage::getModel("bluecom_moduslink/system_config_source_paymentMethods")->toOptionArray();

if(!empty($arrMethods)):
?>

    <ul class="ml-items">
        <?php foreach ($arrMethods as $strMethod):$id  = strtolower($strMethod); ?>
            <li class="item">
                <input type="radio" name="payment[md_payment_method]" value="<?php echo $strMethod  ?>" id="<?php echo $id  ?>" />
                <label for="<?php echo $id  ?>"><?php echo $sourceModel[$strMethod]["label"]  ?></label>
            </li>
        <?php endforeach; ?>
    </ul>

<?php endif; ?>

</div>
