<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3 class="icon-head head-products"><?php echo $this->__('Manage Categories')?></h3></td>
            <td class="a-right">
                <button onclick="setLocation('<?php echo $this->getUrl('*/*/add'); ?>')" class="scalable add" type="button"><span><?php echo $this->__('Add category') ?></span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <?php $cates = Mage::getModel('tomblog/category')->getCollection(); ?>
    <?php foreach ($cates as $cate) : ?>
        <?php echo '<h3>'.$cate->getTitle().'</h3>'; ?>
        <?php echo nl2br($cate->getDescription()); ?>
    <?php endforeach; ?>
</div>